Single page app
Technoculture/VVSales pull request #3
Opened 2024-01-02 13:29 UTC by Naveen-g09

- [ ] create a single page only for tasks
- [ ] add feature to drag to refresh the api call for tasks
- [ ] add a time to refresh the api call for tasks (preferably every 5 minutes)
- [ ] tasks will be fetched from api
- [ ] table format is: name, number, city(optional), state(optional), target call count, created at(by default), modified at
- [ ] call-logs should be configured to local database expo sqlite
- [ ] call log databse table : Timestamp [Event at: ], Task ID [foreign key from api table], Call-Type [Event type] {a drop down with options outgoing, incoming, missed, unable to connect}, Duration of call

### Tech stack 

> Drizzle
> Expo-Sqlite

##Process

@sutyum sir update this, so it will be clear to me and will help me to learn

2024-01-02 15:42 UTC, sutyum commented
- [ ] Use react query and drizzle to interface with sqlite instances
- [ ] Add expo-sqlite and turso to interface through Drizzle
- [ ] add function to sync CallLogs from mobile to cloud
- [ ] add function to sync CallTasks from cloud to mobile
- [ ] Fetch call logs from phone prepare to push to db
- [ ] Trigger both syncs on refresh
- [ ] add pull on refresh to the list

2024-01-05 18:04 UTC, Naveen-g09 commented
@sutyum sir add comments in the code, wherever you feel something is lacking, will fix it first thing in morning

2024-01-05 18:11 UTC, sutyum commented
> @sutyum sir add comments in the code, wherever you feel something is lacking, will fix it first thing in morning

is it working?

2024-01-05 18:23 UTC, sutyum requested changes
Your code is looking fine for what is needed here, as long as it works. I have avoided adding unnecessary improvements that you can make as we need to ship this fast and move to ella

2024-01-05 18:23 UTC, sutyum commented on app/(tabs)/_layout.tsx
> +                    className={`mr-15 ${
https://github.com/dcastil/tailwind-merge

2024-01-05 18:23 UTC, sutyum commented on anything.ts
?

2024-01-05 18:23 UTC, sutyum commented on app/[...missing].tsx
> +        <Link href="/" className="mt-15 py-15">
This sort of styling will break on various screens, consider using auto margins instead

2024-01-05 18:23 UTC, sutyum commented on database.ts
pending deletion

2024-01-05 18:23 UTC, sutyum commented on drizzle/index.ts
> +import { callLogs, tasks } from "./schema";
'tasks' is defined but never used

2024-01-05 18:23 UTC, sutyum commented on lib/client.ts
looks good

2024-01-05 18:23 UTC, sutyum commented on metro.config.js
> +config.resolver.sourceExts.push("sql");
?

2024-01-05 18:23 UTC, sutyum commented on react-native-call-log.d.ts
nice

2024-01-05 18:25 UTC, Naveen-g09 commented
> > @sutyum sir add comments in the code, wherever you feel something is lacking, will fix it first thing in morning
> 
> is it working?

Nope, we figured out way to configure dual databases, and called sync function 

>some part of it is left
Migrations are working 
So hopefully it will be done in the first half

2024-01-05 18:44 UTC, Naveen-g09 commented on anything.ts
me and prince were testing the db, will remove in next commit
it didn't work.

2024-01-05 18:54 UTC, Naveen-g09 commented on anything.ts
deleted it

2024-01-06 13:32 UTC, Naveen-g09 commented
@sutyum sir please guide on work ahead
I believe zod implementation on schema is left and fetch and get request need to be refactored
currently it is a mess, If it is a 2 hours work, I will be do it tommorrow
Please guide me on how to resolve android bundling issue
![image](https://github.com/Technoculture/VVSales/assets/76151123/024da133-ec82-445f-b320-4fb297c71331)

2024-01-10 15:58 UTC, closed without merging